=== w1cmc/robfit/schemas/nuclides.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified">

  <xs:annotation>
    <xs:documentation>
      ROBFIT Nuclide Library Schema
      
      Defines the structure for the nuclide emission line library.
      Contains gamma-ray and X-ray energies and intensities for
      isotopes used in template fitting for nuclide identification
      and quantification.
      
      Replaces individual .pgs files with a single nuclides.xml file.
    </xs:documentation>
  </xs:annotation>

  <!-- Root element -->
  <xs:element name="Nuclides" type="NuclidesType"/>

  <!-- Nuclides container -->
  <xs:complexType name="NuclidesType">
    <xs:sequence>
      <xs:element name="Nuclide" type="NuclideType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    
    <!-- Library version -->
    <xs:attribute name="Version" type="xs:string" use="optional"/>
    
    <!-- Primary data source -->
    <xs:attribute name="Source" type="xs:string" use="optional"/>
    
    <!-- Date library was generated/updated -->
    <xs:attribute name="Date" type="xs:date" use="optional"/>
  </xs:complexType>

  <!-- Individual nuclide entry -->
  <xs:complexType name="NuclideType">
    <xs:sequence>
      <xs:element name="Line" type="LineType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    
    <!-- Nuclide identifier (e.g., "Cs137", "Co60", "Ho166") -->
    <xs:attribute name="Name" type="NuclideNameType" use="required"/>
    
    <!-- Metastable state indicator -->
    <xs:attribute name="Isomer" type="xs:boolean" default="false"/>
    
    <!-- Half-life with unit -->
    <xs:attribute name="HalfLife" type="HalfLifeType" use="optional"/>
    
    <!-- Atomic number -->
    <xs:attribute name="Z" type="xs:positiveInteger" use="optional"/>
    
    <!-- Mass number -->
    <xs:attribute name="A" type="xs:positiveInteger" use="optional"/>
    
    <!-- Reference to data source if different from library default -->
    <xs:attribute name="Source" type="xs:string" use="optional"/>
  </xs:complexType>

  <!-- Emission line -->
  <xs:complexType name="LineType">
    <!-- Energy in keV -->
    <xs:attribute name="E" type="EnergyType" use="required"/>
    
    <!-- Intensity (probability per decay) -->
    <xs:attribute name="I" type="IntensityType" use="required"/>
    
    <!-- Line type: gamma, X-ray, annihilation, etc. -->
    <xs:attribute name="Type" type="LineTypeEnum" use="required"/>
    
    <!-- Originating nuclide if different from parent (e.g., decay daughters) -->
    <xs:attribute name="Origin" type="xs:string" use="optional"/>
    
    <!-- Uncertainty in energy (keV) -->
    <xs:attribute name="dE" type="xs:decimal" use="optional"/>
    
    <!-- Uncertainty in intensity -->
    <xs:attribute name="dI" type="xs:decimal" use="optional"/>
  </xs:complexType>

  <!-- Nuclide identifier pattern: Element + Mass number -->
  <xs:simpleType name="NuclideNameType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z][a-z]?[0-9]{1,3}"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Energy in keV (positive decimal) -->
  <xs:simpleType name="EnergyType">
    <xs:restriction base="xs:decimal">
      <xs:minExclusive value="0"/>
      <xs:maxInclusive value="20000"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Intensity (can exceed 1.0 for summed lines) -->
  <xs:simpleType name="IntensityType">
    <xs:restriction base="xs:decimal">
      <xs:minInclusive value="0"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Half-life with unit suffix -->
  <xs:simpleType name="HalfLifeType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]+\.?[0-9]*(s|m|h|d|y|ms|us|ns)"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Emission line types -->
  <xs:simpleType name="LineTypeEnum">
    <xs:restriction base="xs:string">
      <!-- Gamma rays -->
      <xs:enumeration value="G"/>      <!-- Generic gamma -->
      <xs:enumeration value="P"/>      <!-- Photopeak gamma -->
      
      <!-- X-rays (K-shell) -->
      <xs:enumeration value="XKa1"/>
      <xs:enumeration value="XKa2"/>
      <xs:enumeration value="XKa3"/>
      <xs:enumeration value="XKb1"/>
      <xs:enumeration value="XKb2"/>
      <xs:enumeration value="XKb3"/>
      <xs:enumeration value="XKb4"/>
      <xs:enumeration value="XKb5"/>
      
      <!-- X-rays (L-shell) -->
      <xs:enumeration value="XLa1"/>
      <xs:enumeration value="XLa2"/>
      <xs:enumeration value="XLb1"/>
      <xs:enumeration value="XLb2"/>
      <xs:enumeration value="XLb3"/>
      <xs:enumeration value="XLb4"/>
      <xs:enumeration value="XLb6"/>
      <xs:enumeration value="XLg1"/>
      <xs:enumeration value="XLg2"/>
      <xs:enumeration value="XLg3"/>
      <xs:enumeration value="XLl"/>
      <xs:enumeration value="XLh"/>
      
      <!-- Annihilation -->
      <xs:enumeration value="A"/>      <!-- 511 keV annihilation -->
      
      <!-- Sum peaks -->
      <xs:enumeration value="S"/>      <!-- Sum peak -->
      
      <!-- Escape peaks -->
      <xs:enumeration value="SE"/>     <!-- Single escape -->
      <xs:enumeration value="DE"/>     <!-- Double escape -->
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== w1cmc/robfit/nuclides.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ROBFIT Nuclide Emission Library
  
  Converted from individual .pgs files.
  Contains gamma-ray and X-ray emission data for nuclides
  used in spectral analysis and template fitting.
-->
<Nuclides xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="schemas/nuclides.xsd"
          Version="1.0"
          DataSource="ROBFIT .pgs files">

  <!-- ==================== Daughter Nuclides ==================== -->
  <!-- Referenced by Origin attributes but not in original .pgs files -->

  <Nuclide Name="Ag109m" Element="Ag" A="109" Isomer="true">
    <!-- Lines from parent nuclides reference this daughter -->
  </Nuclide>

  <Nuclide Name="Ba137m" Element="Ba" A="137" Isomer="true">
    <!-- Lines from parent nuclides reference this daughter -->
  </Nuclide>

  <Nuclide Name="In113m" Element="In" A="113" Isomer="true">
    <!-- Lines from parent nuclides reference this daughter -->
  </Nuclide>

  <!-- ==================== Primary Nuclides ==================== -->

  <Nuclide Name="Ag105" Element="Ag" A="105">
    <Line E="38.72" I="5.382e-05" Type="P"/>
    <Line E="63.98" I="0.104742" Type="P"/>
    <Line E="73.5" I="0.0001449" Type="P"/>
    <Line E="89.91" I="0.0001449" Type="P"/>
    <Line E="112.43" I="0.0002277" Type="P"/>
    <Line E="155.39" I="0.0043884" Type="P"/>
    <Line E="158.92" I="0.0002277" Type="P"/>
    <Line E="167.5" I="0.00015318" Type="P"/>
    <Line E="182.85" I="0.003519" Type="P"/>
    <Line E="202.13" I="0.00013248" Type="P"/>
    <Line E="216.17" I="0.0002277" Type="P"/>
    <Line E="270.5" I="0.0001242" Type="P"/>
    <Line E="280.44" I="0.30222" Type="P"/>
    <Line E="284.83" I="0.0009522" Type="P"/>
    <Line E="289.18" I="0.0013248" Type="P"/>
    <Line E="306.25" I="0.0087768" Type="P"/>
    <Line E="311.64" I="0.0006003" Type="P"/>
    <Line E="319.16" I="0.04347" Type="P"/>
    <Line E="325.26" I="0.0016146" Type="P"/>
    <Line E="328.61" I="0.0015318" Type="P"/>
    <Line E="331.51" I="0.040986" Type="P"/>
    <Line E="344.52" I="0.414" Type="P"/>
    <Line E="354.0" I="6.624e-05" Type="P"/>
    <Line E="360.66" I="0.004968" Type="P"/>
    <Line E="370.17" I="0.0073278" Type="P"/>
    <Line E="382.6" I="4.554e-05" Type="P"/>
    <Line E="392.64" I="0.0198306" Type="P"/>
    <Line E="401.65" I="0.0017388" Type="P"/>
    <Line E="408.0" I="0.00040158" Type="P"/>
    <Line E="414.66" I="0.0028566" Type="P"/>
    <Line E="420.94" I="0.00104742" Type="P"/>
    <Line E="437.12" I="0.002484" Type="P"/>
    <Line E="442.25" I="0.047196" Type="P"/>
    <Line E="443.37" I="0.104742" Type="P"/>
    <Line E="446.74" I="0.001242" Type="P"/>
    <Line E="486.8" I="6.21e-05" Type="P"/>
    <Line E="527.2" I="0.00100188" Type="P"/>
    <Line E="560.72" I="0.0058374" Type="P"/>
    <Line E="564.39" I="7.038e-05" Type="P"/>
    <Line E="576.62" I="0.0002898" Type="P"/>
    <Line E="580.1" I="8.28e-05" Type="P"/>
    <Line E="582.93" I="0.00017802" Type="P"/>
    <Line E="598.6" I="0.0001449" Type="P"/>
    <Line E="610.0" I="8.28e-05" Type="P"/>
    <Line E="617.85" I="0.0115506" Type="P"/>
    <Line E="640.5" I="0.0002898" Type="P"/>
    <Line E="644.55" I="0.110538" Type="P"/>
    <Line E="646.0" I="0.0006624" Type="P"/>
    <Line E="649.2" I="3.726e-05" Type="P"/>
    <Line E="650.72" I="0.0253782" Type="P"/>
    <Line E="673.21" I="0.0104742" Type="P"/>
    <Line E="681.9" I="0.00044712" Type="P"/>
    <Line E="727.22" I="0.001242" Type="P"/>
    <Line E="743.31" I="0.0057132" Type="P"/>
    <Line E="796.25" I="2.898e-05" Type="P"/>
    <Line E="807.46" I="0.0115506" Type="P"/>
    <Line E="844.89" I="0.00045954" Type="P"/>
    <Line E="860.33" I="2.898e-05" Type="P"/>
    <Line E="921.04" I="0.0004554" Type="P"/>
    <Line E="928.89" I="0.00016146" Type="P"/>
    <Line E="962.43" I="0.001242" Type="P"/>
    <Line E="1087.94" I="0.038502" Type="P"/>
    <Line E="1125.7" I="0.00014076" Type="P"/>
  </Nuclide>

  <Nuclide Name="Am241" Element="Am" A="241">
    <Line E="11.871" I="0.0066" Type="XLl"/>
    <Line E="13.761" I="0.0107" Type="XLa2"/>
    <Line E="13.946" I="0.096" Type="XLa1"/>
    <Line E="15.861" I="0.00153" Type="XLh"/>
    <Line E="16.109" I="0.00184" Type="XLb6"/>
    <Line E="16.816" I="0.025" Type="XLb2"/>
    <Line E="17.061" I="0.015" Type="XLb4"/>
    <Line E="17.505" I="0.0065" Type="XLb5"/>
    <Line E="17.751" I="0.057" Type="XLb1"/>
    <Line E="17.992" I="0.0137" Type="XLb3"/>
    <Line E="20.784" I="0.0139" Type="XLg1"/>
    <Line E="21.099" I="0.0065" Type="XLg2"/>
    <Line E="21.342" I="0.0059" Type="XLg3"/>
    <Line E="21.491" I="0.0029" Type="XLg1"/>
    <Line E="26.3448" I="0.024" Type="P"/>
    <Line E="32.183" I="1.74e-05" Type="P"/>
    <Line E="33.1964" I="0.00126" Type="P"/>
    <Line E="42.73" I="5.5e-05" Type="P"/>
    <Line E="43.423" I="0.00073" Type="P"/>
    <Line E="51.01" I="2.6e-07" Type="P"/>
    <Line E="55.56" I="0.000181" Type="P"/>
    <Line E="57.85" I="5.2e-05" Type="P"/>
    <Line E="59.5412" I="0.359" Type="P"/>
    <Line E="64.83" I="1.45e-06" Type="P"/>
    <Line E="67.45" I="4.2e-06" Type="P"/>
    <Line E="69.76" I="2.9e-05" Type="P"/>
    <Line E="75.9" I="6e-06" Type="P"/>
    <Line E="96.242" I="2.8e-07" Type="XKa3"/>
    <Line E="96.79" I="4.7e-07" Type="P"/>
    <Line E="97.069" I="8e-05" Type="XKa2"/>
    <Line E="98.97" I="0.000203" Type="P"/>
    <Line E="101.059" I="0.00012" Type="XKa1"/>
    <Line E="102.98" I="0.000195" Type="P"/>
    <Line E="106.42" I="1.5e-07" Type="P"/>
    <Line E="109.7" I="4.9e-08" Type="P"/>
    <Line E="113.303" I="1.5e-05" Type="XKb3"/>
    <Line E="114.234" I="2.8e-05" Type="XKb1"/>
    <Line E="114.912" I="1.1e-06" Type="XKb5"/>
    <Line E="117.463" I="1.1e-05" Type="XKb2"/>
    <Line E="117.875" I="4e-06" Type="XKb4"/>
    <Line E="120.36" I="4.5e-08" Type="P"/>
    <Line E="139.44" I="5.3e-08" Type="P"/>
    <Line E="146.55" I="4.61e-06" Type="P"/>
    <Line E="150.04" I="7.4e-07" Type="P"/>
    <Line E="154.27" I="5e-09" Type="P"/>
    <Line E="159.26" I="1.4e-08" Type="P"/>
    <Line E="161.54" I="1.5e-08" Type="P"/>
    <Line E="164.61" I="6.67e-07" Type="P"/>
    <Line E="165.81" I="2.32e-07" Type="P"/>
    <Line E="169.56" I="1.73e-06" Type="P"/>
    <Line E="175.07" I="1.82e-07" Type="P"/>
    <Line E="190.4" I="2.2e-08" Type="P"/>
    <Line E="191.96" I="2.16e-07" Type="P"/>
    <Line E="197.0" I="4.9e-09" Type="P"/>
    <Line E="201.7" I="8e-09" Type="P"/>
    <Line E="204.06" I="2.9e-08" Type="P"/>
    <Line E="208.0" I="7.91e-06" Type="P"/>
    <Line E="221.46" I="4.24e-07" Type="P"/>
    <Line E="232.81" I="4.6e-08" Type="P"/>
    <Line E="234.4" I="7e-09" Type="P"/>
    <Line E="246.73" I="2.42e-08" Type="P"/>
    <Line E="249.0" I="5e-09" Type="P"/>
    <Line E="260.8" I="1.21e-08" Type="P"/>
    <Line E="264.89" I="9e-08" Type="P"/>
    <Line E="267.54" I="2.63e-07" Type="P"/>
    <Line E="270.63" I="6.4e-09" Type="P"/>
    <Line E="271.54" I="1.44e-08" Type="P"/>
    <Line E="275.77" I="6.6e-08" Type="P"/>
    <Line E="278.04" I="4.4e-09" Type="P"/>
    <Line E="291.3" I="3.1e-08" Type="P"/>
    <Line E="292.77" I="1.42e-07" Type="P"/>
    <Line E="304.21" I="1.01e-08" Type="P"/>
    <Line E="309.1" I="1.4e-08" Type="P"/>
    <Line E="322.52" I="1.52e-06" Type="P"/>
    <Line E="324.69" I="1.8e-08" Type="P"/>
    <Line E="329.69" I="1.1e-08" Type="P"/>
    <Line E="332.36" I="1.49e-06" Type="P"/>
    <Line E="335.38" I="4.96e-06" Type="P"/>
    <Line E="337.7" I="4.29e-08" Type="P"/>
    <Line E="340.56" I="4.3e-08" Type="P"/>
    <Line E="350.71" I="1.39e-08" Type="P"/>
    <Line E="358.25" I="1.2e-08" Type="P"/>
    <Line E="368.59" I="2.17e-06" Type="P"/>
    <Line E="370.94" I="5.23e-07" Type="P"/>
    <Line E="374.83" I="3.13e-08" Type="P"/>
    <Line E="376.65" I="1.38e-06" Type="P"/>
    <Line E="383.81" I="2.82e-07" Type="P"/>
    <Line E="389.0" I="4.9e-09" Type="P"/>
    <Line E="390.62" I="5.9e-08" Type="P"/>
    <Line E="398.64" I="2e-08" Type="P"/>
    <Line E="401.0" I="4.9e-09" Type="P"/>
    <Line E="406.35" I="1.45e-08" Type="P"/>
    <Line E="411.27" I="1.8e-09" Type="P"/>
    <Line E="415.88" I="3.1e-08" Type="P"/>
    <Line E="419.33" I="2.87e-07" Type="P"/>
    <Line E="426.47" I="2.46e-07" Type="P"/>
    <Line E="429.94" I="1.15e-08" Type="P"/>
    <Line E="440.63" I="5.6e-09" Type="P"/>
    <Line E="442.81" I="3.5e-08" Type="P"/>
    <Line E="446.43" I="4.9e-09" Type="P"/>
    <Line E="452.6" I="2.4e-08" Type="P"/>
    <Line E="454.66" I="9.7e-08" Type="P"/>
    <Line E="459.68" I="3.6e-08" Type="P"/>
    <Line E="463.22" I="1e-08" Type="P"/>
    <Line E="468.12" I="2.88e-08" Type="P"/>
    <Line E="485.91" I="1e-08" Type="P"/>
    <Line E="487.3" I="4.4e-09" Type="P"/>
    <Line E="494.39" I="1e-09" Type="P"/>
    <Line E="501.39" I="1.4e-09" Type="P"/>
    <Line E="512.5" I="1.15e-08" Type="P"/>
    <Line E="514.0" I="2.6e-08" Type="P"/>
    <Line E="522.06" I="9e-09" Type="P"/>
    <Line E="525.14" I="1.6e-09" Type="P"/>
    <Line E="529.17" I="4.6e-09" Type="P"/>
    <Line E="532.44" I="8e-10" Type="P"/>
    <Line E="545.4" I="7e-09" Type="P"/>
    <Line E="546.12" I="2.5e-09" Type="P"/>
    <Line E="548.15" I="5e-10" Type="P"/>
    <Line E="555.25" I="9e-10" Type="P"/>
    <Line E="563.05" I="7e-09" Type="P"/>
    <Line E="573.94" I="1.25e-08" Type="P"/>
    <Line E="582.6" I="2.3e-09" Type="P"/>
    <Line E="586.59" I="1.31e-08" Type="P"/>
    <Line E="590.28" I="2.86e-08" Type="P"/>
    <Line E="597.48" I="7.4e-08" Type="P"/>
    <Line E="600.26" I="2.2e-09" Type="P"/>
    <Line E="619.01" I="5.94e-07" Type="P"/>
    <Line E="627.18" I="5.6e-09" Type="P"/>
    <Line E="632.93" I="1.26e-08" Type="P"/>
    <Line E="636.9" I="2.1e-09" Type="P"/>
    <Line E="641.47" I="7.1e-08" Type="P"/>
    <Line E="653.02" I="3.77e-07" Type="P"/>
    <Line E="662.4" I="3.64e-06" Type="P"/>
    <Line E="666.5" I="4.9e-09" Type="P"/>
    <Line E="669.83" I="3.8e-09" Type="P"/>
